---
- name: remediation phase
  hosts: all
  tasks:
    - name: Ensure application is existed in nginx server
      ansible.builtin.copy:
        remote_src: true
        src: /root/haikm/Flappy-Bird
        dest: /usr/share/nginx/html/

