---
- name: remidiation
  hosts: all
  tasks:
    - name: get service facts
      ansible.builtin.service_facts:
    - name: print service facts
      ansible.builtin.debug:
        var: ansible_facst.services
